  # spring-boot-docker/docker-compose.yml
  version: "3.7"
  services:
    mysql-service:
      image: mysql:5.7
      networks:
        - spring-boot-mysql-network
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=1Aefqsae
        - MYSQL_DATABASE=eccomerce-pulse
      ports:
        - 3307:3306
      volumes:
      - ./docker/volumes_mysql:/var/lib/mysql
    web-service:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      networks:
        - spring-boot-mysql-network
      depends_on:
        - mysql-service
  networks:
    spring-boot-mysql-network:
      driver: bridge
